### ISSUE TITLE
has-changes doesn't work as expected

### ISSUE THREAD

**Issue by tnqn** [antrea-io/has-changes#7]
It return `yes` somehow when all changed files match the ignore_patterns. "hack/.notableofcontents" is mismatched:
```
PATHS: *
IGNORE_PATHS: docs/* ci/jenkins/* *.md hack/.notableofcontents plugins/*

...

* Changed files are:
docs/antctl.md
docs/multicluster/antctl.md
hack/.notableofcontents
* Changed files after filtering with patterns are:
docs/antctl.md docs/multicluster/antctl.md hack/.notableofcontents
* Changed files after filtering with ignore_patterns are:
hack/.notableofcontents
Setting 'has_changes' to 'yes'
```

See the following builds:
https://github.com/antrea-io/antrea/runs/5692577240?check_suite_focus=true
https://github.com/antrea-io/antrea/runs/5692570263?check_suite_focus=true

However, I cannot reproduce the issue by calling `check_changes.sh` directly, not sure what's wrong.

**Comment by antoninbas** [comment]
Thanks for reporting this, I'll see if I can figure it out

**Comment by antoninbas** [comment]
@tnqn it should be fixed now

The v2 tag now points to the v2.0.1 release which means Antrea should pick up the change automatically.
